---
stoplight-id: dp15zhxks2i84
---

@startuml organizational-entities

package OrganizationPresenter {
  
  entity Organization {
    related OrganizationRelation
  }
  
  entity OrganizationData {
    name String
    slug String
  }
  Organization *-- OrganizationData

  entity OrganizationMetadata {
    id Int
    type OrganizationType
    external_id String
    created_at DateTime
    updated_at DateTime
  }
  Organization *-- OrganizationMetadata

  entity OrganizationRelation {
    projects OrgProjectsRelation
    users OrgUsersRelation
    launches OrgLaunchesRelation
    billing OrgBillingRelation
  }
  OrganizationRelation -up- Organization

  entity OrgProjectsRelation {
    count Int
  }
  OrgProjectsRelation -up- OrganizationRelation

  entity OrgUsersRelation {
    count Int
  }
  OrgUsersRelation -up- OrganizationRelation

  entity OrgLaunchesRelation {
    last_occurred_at DateTime
  }
  OrgLaunchesRelation -up- OrganizationRelation

  entity OrgBillingRelation {
    plan_name String
    storage_usage Int
  }
  OrgBillingRelation -up- OrganizationRelation

  enum OrganizationType {
    INTERNAL
    PERSONAL
    EXTERNAL
  }
  OrganizationMetadata -- OrganizationType
  
}

package OrganizationUserPresenter {

  entity OrganizationUser

  entity OrganizationUserDefinition {
    projects List<OrganizationUserProject>
  }

  entity OrganizationUserData {
    email String
    role OrgRole
  }
  OrganizationUserData -up-o OrganizationUser
  OrganizationUserData -up-o OrganizationUserDefinition

  entity OrganizationUserInfo {
    full_name String
    projects_info OrganizationUserProjectsInfo
  }
  OrganizationUserInfo -up-* OrganizationUser

  enum OrgRole {
    PROJECT_MANAGER
    OrganizationUser
  }
  OrgRole -up-* OrganizationUserData

  entity OrganizationUserProjectsInfo {
    count Int
  }
  OrganizationUserProjectsInfo -up-* OrganizationUserInfo

  entity OrganizationUserProject {
    id Int
    key String
    role ProjectRole
  }
  OrganizationUserProject -up- OrganizationUserDefinition

  enum ProjectRole {
    EDITOR
    VIEWER
  }
  ProjectRole -up-* OrganizationUserProject
}

package UserPresenter {
  entity User

  entity UserMetadata {
    id Int
    type UserType
    created_at DateTime
    updated_at DateTime
    last_active_at DateTime
  }
  UserMetadata -up-o OrganizationUser
  UserMetadata -up-o User

  enum UserType {
    USER
    ADMIN
  }
  UserType -up-* UserMetadata

}

@enduml