---
stoplight-id: dp15zhxks2i84
---

@startuml organizational-entities

frame OrganizationPresenter {

  entity OrganizationDefinition {
    name String
    slug String
  }

  entity OrganizationMetadata {
    id Int
    type OrganizationType
    created_at DateTime
    updated_at DateTime
  }

  entity OrganizationInfo {
    projects_info OrgProjectsInfo
    members_info OrgMembersInfo
    launches_info OrgLaunchesInfo
    billing_info OrgBillingInfo
  }

  entity OrgProjectsInfo {
    total_count Int
  }
  OrgProjectsInfo -up- OrganizationInfo

  entity OrgMembersInfo {
    total_count Int
  }
  OrgMembersInfo -up- OrganizationInfo

  entity OrgLaunchesInfo {
    last_occurred_at DateTime
  }
  OrgLaunchesInfo -up- OrganizationInfo

  entity OrgBillingInfo {
    plan_name String
    storage_usage Int
  }
  OrgBillingInfo -up- OrganizationInfo

  enum OrganizationType {
    INTERNAL
    PERSONAL
    UPSA
  }
  OrganizationMetadata -- OrganizationType

  entity Organization
  Organization *-- OrganizationDefinition
  Organization *-- OrganizationMetadata
  Organization *-- OrganizationInfo

}

frame Members {

  entity Member {
    id Int
    email String
    name String
    type UserType
    role UserRole
    projects List<MemberProject>
  }

  enum UserType {
    USER
    ADMIN
  }
  UserType -up- Member

  enum UserRole {
    PROJECT_MANAGER
    MEMBER
  }
  UserRole -up- Member

  entity MemberProject {
  }
  MemberProject -up- Member

}

@enduml