openapi: 3.1.0
x-stoplight:
  id: fwzsq6mjrpzhc
info:
  title: API Keys
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api-keys/:
    parameters: []
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/ApiKeyMetadata'
      operationId: get-users-userId-api-keys
    post:
      summary: ''
      operationId: post-users-userId-api-keys
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiKey'
  '/api-keys/{key_id}':
    parameters:
      - schema:
          type: string
        name: key_id
        in: path
        required: true
    delete:
      summary: ''
      operationId: delete-users-user_id-api-keys-key_id
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiKeyMetadata'
components:
  schemas:
    ApiKeyMetadata:
      title: ApiKey Metadata
      x-stoplight:
        id: 68ded9191b195
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        created_at:
          type: string
          format: date-time
    ApiKey:
      allOf:
        - $ref: '#/components/schemas/ApiKeyMetadata'
        - type: object
          properties:
            key:
              type: string
