openapi: 3.1.0
info:
  title: API Keys
  version: '0.1'
  description: API for working with API Keys resources
  contact:
    name: ReportPortal Team
    url: 'https://reportportal.io'
    email: support@reportportal.io
servers:
  - url: 'https://demo.reportportal.io'
paths: {}
components:
  schemas:
    ApiKeyMetadata:
      title: Api key metadata
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        user_id:
          type: integer
        created_at:
          type: integer
    ApiKey:
      allOf:
        - $ref: '#/components/schemas/ApiKeyMetadata'
        - type: object
          properties:
            api_key:
              type: string
        - required:
            - id
            - name
            - user_id
            - created_at
            - api_key
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
