openapi: 3.0.0
info:
  title: API Keys
  version: '0.1'
  description: API for working with API Keys resources
  contact:
    name: ReportPortal Team
    url: 'https://reportportal.io'
    email: support@reportportal.io
  license:
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
    name: Apache 2.0
servers:
  - url: 'https://demo.reportportal.io'
paths: {}
components:
  schemas:
    ApiKeyMetadata:
      title: API Key metadata
      type: object
      description: ReportPortal only stores metadata and a hash of the API Key.
      properties:
        id:
          type: integer
          description: Internal identifier
        name:
          type: string
          description: API Key unique name
        user_id:
          type: integer
          description: API Key owner
        created_at:
          type: string
          format: date-time
          description: Data time with milliseconds
          example: '2019-07-30T06:43:40.252Z'
    ApiKey:
      allOf:
        - $ref: '#/components/schemas/ApiKeyMetadata'
        - type: object
          properties:
            api_key:
              type: string
              description: Generated API Key
      description: 'Generated API key, granted once after creation.'
      title: API Key
  securitySchemes:
    API Key:
      type: http
      scheme: bearer
security:
  - API Key: []
