openapi: 3.1.0
x-stoplight:
  id: hpx2e63mc8gcc
info:
  title: Organizations
  version: '0.1'
  description: ''
  summary: API Collection for organizations management
servers:
  - url: 'http://localhost:3000'
paths:
  /organizations:
    get:
      summary: Get a list of organizations
      tags:
        - Organizations
        - Ready for implementation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ./models/Offset.yaml
                  - x-stoplight:
                      id: nsdfmhu6y0tgj
                    type: object
                    properties:
                      items:
                        x-stoplight:
                          id: p6c0g6dra4c11
                        type: array
                        items:
                          $ref: '#/components/schemas/OrganizationProfile'
                          x-stoplight:
                            id: 8zm4xnkiool8l
                description: The list of organizations
      operationId: get-organizations
      description: Get a list of existing organizations.
      parameters:
        - $ref: '#/components/parameters/Offset'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Order'
      requestBody:
        content: {}
    post:
      summary: Create a new organization
      operationId: post-organizations
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationProfile'
        '402':
          description: Payment Required
      description: |-
        > **Enterprise edition feature** 
        >
        > Available only if an Organization plugin is enabled.

        Create a new organization. Provide name and slug.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationDetails'
        description: |-
          You can create an organization provide name and slug.
          If the slug is not provided, it will be generated from the name.
      tags:
        - Organizations
        - Ready for implementation
  '/organizations/{org_id}':
    get:
      summary: Get organization information
      tags:
        - Organizations
        - Ready for implementation
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationProfile'
      operationId: get-organizations-org_id
      description: Provide organization information.
    parameters:
      - $ref: '#/components/parameters/OrganizationId'
    put:
      summary: Update organization
      operationId: put-organizations-org_id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationProfile'
        '402':
          description: Payment Required
      description: |-
        > **Enterprise edition feature** 
        >
        > Available only if an Organization plugin is enabled.

        Update organization information with the provided data.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganizationDetails'
        description: ''
      tags:
        - Organizations
        - Ready for implementation
      x-internal: false
    patch:
      summary: Partial organization update
      operationId: patch-organizations-org_id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationProfile'
        '402':
          description: Payment Required
      description: |-
        > **Enterprise edition feature** 
        >
        > Available only if an Organization plugin is enabled.

        Particular organization fields update via the [JSON Merge Patch standard](https://datatracker.ietf.org/doc/html/rfc7386).
      requestBody:
        content:
          application/merge-patch+json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  x-stoplight:
                    id: 6906m5222zvx6
                slug:
                  type: string
                  x-stoplight:
                    id: gt4uavhbr5qq9
        description: 'Use PATCH with JSON Merge Patch standard, a specialized media type application/merge-patch+json for partial resource representation to update parts of resource objects.'
      tags:
        - Organizations
        - Ready for implementation
      x-internal: false
    delete:
      summary: Delete organization
      operationId: delete-organizations-org_id
      responses:
        '204':
          description: No Content
        '402':
          description: Payment Required
      description: |-
        > **Enterprise edition feature** 
        >
        > Available only if an Organization plugin is enabled.

        Delete organization by identifier.
      tags:
        - Organizations
        - Ready for implementation
      x-internal: false
components:
  schemas:
    OrganizationProfile:
      title: Organization
      x-stoplight:
        id: lzs7p3khz8n9d
      examples: []
      description: Organization complete information.
      allOf:
        - $ref: '#/components/schemas/OrganizationInfo'
          x-stoplight:
            id: 64kdwn8nva4jg
        - type: object
          x-stoplight:
            id: mlbwuzzsovyma
          properties:
            related:
              $ref: '#/components/schemas/OrganizationRelation'
              x-stoplight:
                id: 2j23biyi2hfqo
    OrganizationInfo:
      title: Organization
      x-stoplight:
        id: x7vdhfbeaz5pu
      examples: []
      description: Organization complete information.
      allOf:
        - $ref: '#/components/schemas/OrganizationDetails'
          x-stoplight:
            id: 64kdwn8nva4jg
        - $ref: '#/components/schemas/OrganizationMetadata'
          x-stoplight:
            id: 2bhjwvbwlhrlb
    OrganizationDetails:
      title: Organization definition
      x-stoplight:
        id: 2gyt1v3d2gfmm
      type: object
      examples: []
      description: Basic information provided by the client.
      properties:
        name:
          type: string
          x-stoplight:
            id: dz5igu0m6iy9o
          description: Organization display name.
        slug:
          type: string
          x-stoplight:
            id: hsav6x2ci2qt1
          description: |-
            Unique identifying part.
            Generated according to the organization name if not specified by the user.
          pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$'
      required:
        - name
    OrganizationMetadata:
      title: Organization metadata
      x-stoplight:
        id: 08jgykhqykh7b
      description: Organization metadata. Represent generated fields.
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Organization ReportPortal ID.
        type:
          type: string
          x-stoplight:
            id: 4nf6lordbrqag
          enum:
            - INTERNAL
            - PERSONAL
            - EXTERNAL
          description: |-
            Type for automatization purposes.

            There are three types:
            - INTERNAL: created by API request.
            - PERSONAL: created for a user after the user creating. Only Enterprise edition feature.
            - EXTERNAL: created for external integrations.
        external_id:
          type: string
          x-stoplight:
            id: m0wvgkfndhpag
        created_at:
          type: string
          x-stoplight:
            id: murxta40l19cz
          format: date-time
          description: Creation date.
        updated_at:
          type: string
          x-stoplight:
            id: wy58s9p7s4l81
          format: date-time
          description: Last update date.
    OrganizationRelation:
      title: Organization relations
      x-stoplight:
        id: mvjaoy2fofepj
      type: object
      description: Related information about the organization.
      properties:
        users:
          x-stoplight:
            id: aau80pjhj0ecs
          description: General information about the organization users.
          type: object
          properties:
            count:
              type: integer
              x-stoplight:
                id: wqrlqc1knwtwb
              description: Total count of users in the organization.
              minimum: 0
        projects:
          type: object
          x-stoplight:
            id: gfcxxarpmzbsn
          description: General information about the organization projects.
          properties:
            count:
              type: integer
              x-stoplight:
                id: ypqfuxxevu2si
              minimum: 0
              description: Total count of projects in the organization.
        launches:
          type: object
          x-stoplight:
            id: cz8q9j1tg4ak0
          description: General information about the organization launches.
          properties:
            last_occurred_at:
              type: string
              x-stoplight:
                id: ry81p33pd7rr1
              format: date-time
              description: Last launch occurrence date.
        billing:
          type: object
          x-stoplight:
            id: kp0guqf27icwi
          description: |-
            General information about the organization billing.
            Available only if a Billing plugin is enabled.
          properties:
            plan_name:
              type: string
              x-stoplight:
                id: dg7lhxj6xspo9
              description: Plan name.
            storage_usage:
              type: integer
              x-stoplight:
                id: vbbgb3u6pyequ
              minimum: 0
              maximum: 100
              description: Storage usage in percents.
    OrganizationUserInfo:
      title: Organization user information
      x-stoplight:
        id: snwrtcmq8wvt1
      allOf:
        - $ref: '#/components/schemas/OrganizationUserDetails'
        - $ref: '#/components/schemas/OrganizationUserMetadata'
          x-stoplight:
            id: 0ao0t2fs2p7gc
      description: Related information about user in organization.
    OrganizationUserDetails:
      title: Organization user
      x-stoplight:
        id: 5nqrewxfku9tn
      type: object
      properties:
        role:
          type: string
          x-stoplight:
            id: 3v2e1cyby216c
          enum:
            - PROJECT_MANAGER
            - MEMBER
          description: Organization user's role.
    OrganizationUserMetadata:
      title: Organization user
      x-stoplight:
        id: g7a81q7nu3zgo
      allOf:
        - x-stoplight:
            id: 3b9125n1gljg0
          properties:
            assigned_at:
              type: string
              x-stoplight:
                id: a7gp7z7wei0p6
              format: date-time
            updated_at:
              type: string
              x-stoplight:
                id: a7gp7z7wei0p6
              format: date-time
            last_active_at:
              type: string
              x-stoplight:
                id: a7gp7z7wei0p6
              format: date-time
        - x-stoplight:
            id: 0srgatmno8b4b
          properties:
            related:
              $ref: '#/components/schemas/OrganizationUserRelation'
              x-stoplight:
                id: wrawjhpa10y1j
      type: object
    OrganizationUserRelation:
      title: Organization user relations
      x-stoplight:
        id: 0v55lmrhzuy8t
      type: object
      properties:
        projects:
          type: object
          x-stoplight:
            id: c9yj84iq8c79w
          description: User's projects relation metadata.
          properties:
            count:
              type: integer
              x-stoplight:
                id: 127i76hh550kj
              description: Total number of user's projects in organization.
              minimum: 0
    OrganizationUserAssignment:
      title: Organization user
      x-stoplight:
        id: u52hc1apf7q2q
      allOf:
        - $ref: ./models/user/UserContactData.yaml
          x-stoplight:
            id: fh1989fa101o2
        - $ref: '#/components/schemas/OrganizationUserDetails'
        - type: object
          x-stoplight:
            id: nh1gunacinw5v
          properties:
            projects:
              x-stoplight:
                id: 7qf3duno409l9
              type: array
              items:
                $ref: ./models/project/ProjectUserAssignment.yaml
                x-stoplight:
                  id: fmzilkgtzpdmu
  parameters:
    OrganizationId:
      name: org_id
      in: path
      required: true
      schema:
        type: string
      description: Organization identifier
    Limit:
      name: limit
      in: query
      required: false
      schema:
        type: string
      description: The limit used for this page of results. This will be the same as the limit query parameter unless it exceeded the maximum value allowed for this API endpoint
    Offset:
      name: offset
      in: query
      required: false
      schema:
        type: string
      description: The offset used for this page of results
    Sort:
      name: sort
      in: query
      required: false
      schema:
        type: string
      description: Indicate sort by field
    Order:
      name: order
      in: query
      required: false
      schema:
        type: string
      description: Indicate sorting direction
    UserId:
      name: user_id
      in: path
      required: true
      schema:
        type: string
      description: User identifier
  requestBodies: {}
tags:
  - name: Organizations
  - name: Projects
  - name: Ready for implementation
  - name: Users
