openapi: 3.0.3
info:
  title: ReportPortal Activities API
  version: Organization
  description: API Collection for working with activities.
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  contact:
    name: Reingold Shekhtel
    email: reingold_shekhtel@epam.com
servers:
  - url: '{host}{basePath}'
    description: ReportPortal server
    variables:
      host:
        default: 'https://demo.reportportal.io'
        description: Host name and port (if needed) of Report Portal server
      basePath:
        default: /api
        description: Base path of Report Portal API
security:
  - BearerAuth: []
paths:
  /activities/searches:
    parameters: []
    post:
      summary: Search activities by complex criteria
      operationId: activities-search
      description: |-
        Create search request by activities.

        You can use the following attributes as a `search_criteria[*].filter_key` for filtering:

        - `eventName`
        - `objectType`
        - `objectName`
        - `organizationId`
        - `organizationName`
        - `projectId`
        - `projectName`
        - `subjectType`
        - `subjectName`
        - `createdAt`

        ### Authority

        - `ADMINISTRATOR`
      tags:
        - activities
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/SearchCriteriaRQ.yaml
            example:
              search_criteria:
                - filter_key: projectName
                  operation: EQ
                  value: superadmin_personal
              offset: 0
              limit: 300
              sort: createdAt
              order: DESC
        description: |
          This is a [GET with body payload](https://opensource.zalando.com/restful-api-guidelines/#get-with-body) 
          that doesn't create resources. 
          It returns all activities matching the query passed as the request input payload.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: ../models/Offset.yaml
                  - type: object
                    properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/Activity'
              example:
                items:
                  - id: 1
                    created_at: '2024-03-29T12:29:54.772Z'
                    event_name: updateItem
                    object_id: 1153
                    object_name: Step-1(A)
                    object_type: itemIssue
                    project_id: 1
                    project_name: superadmin_personal
                    subject_name: superadmin
                    subject_type: user
                    subject_id: '1'
                    details:
                      history:
                        - field: status
                          old_value: SKIPPED
                          new_value: FAILED
                offset: 0
                limit: 300
                total_count: 1
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
  '/projects/{project_key}/activities/{activity_id}':
    parameters:
      - schema:
          type: string
        name: project_key
        in: path
        required: true
        description: Project key.
      - schema:
          $ref: ../types/identifier.yaml
        name: activity_id
        in: path
        required: true
        description: Activity identifier.
    get:
      summary: Get project activity by ID
      operationId: getProjectActivity
      description: |-
        Fetches the activity details by its ID for a specific project.

        ### Authority

        - `ADMINISTRATOR`
        - `EDITOR`
        - `VIEWER`
      tags:
        - activities
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectActivity'
              example:
                id: 1
                user: superadmin
                user_id: 1
                logged_object_id: 22
                last_modified: '2024-03-29T15:03:54.156904Z'
                action_type: finishLaunch
                object_type: LAUNCH
                project_id: 1
                project_name: superadmin_personal
                project_key: superadmin_personal
                object_name: 1 step (failed) - filled description
                details:
                  history: []
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
  '/projects/{project_key}/test-items/{item_id}/activities':
    parameters:
      - schema:
          type: string
        name: project_key
        in: path
        required: true
        description: Project key.
      - schema:
          $ref: ../types/identifier.yaml
        name: item_id
        in: path
        required: true
        description: Test item identifier.
    get:
      summary: Get a list of activities for a specific test item
      operationId: getTestItemActivities
      description: |-
        Fetches a list of activities for a specific test item in a project, including
        activities that matched patterns for it.
      tags:
        - activities
      parameters:
        - $ref: ../parameters/Offset.yaml
        - $ref: ../parameters/Limit.yaml
        - $ref: ../parameters/Order.yaml
        - name: sort
          in: query
          required: false
          schema:
            type: string
            default: created_at
          description: Field to sort the activities by.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivitiesPage'
              example:
                items:
                  - id: 1
                    created_at: '2024-03-29T12:29:54.772Z'
                    event_name: updateItem
                    object_id: 1153
                    object_name: Step-1(A)
                    object_type: itemIssue
                    project_id: 1
                    project_name: superadmin_personal
                    subject_name: superadmin
                    subject_type: user
                    subject_id: '1'
                    details:
                      history:
                        - field: status
                          old_value: SKIPPED
                          new_value: FAILED
                offset: 0
                limit: 300
                total_count: 1
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
  '/projects/{project_key}/test-cases/{test_case_id}/activities':
    parameters:
      - schema:
          type: string
        name: project_key
        in: path
        required: true
        description: Project key.
      - schema:
          $ref: ../types/identifier.yaml
        name: test_case_id
        in: path
        required: true
        description: Test case identifier.
    get:
      summary: Get a list of activities for a specific test case
      operationId: getTestCaseActivities
      description: |-
        Fetches a list of activities for a specific test case in a project.
      tags:
        - activities
      parameters:
        - $ref: ../parameters/Offset.yaml
        - $ref: ../parameters/Limit.yaml
        - $ref: ../parameters/Order.yaml
        - name: sort
          in: query
          required: false
          schema:
            type: string
            default: created_at
          description: Field to sort the activities by.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivitiesPage'
              example:
                items:
                  - id: 2
                    created_at: '2024-04-02T09:14:21.331Z'
                    event_name: updateTestCase
                    object_id: 57
                    object_name: 'Login: valid credentials'
                    object_type: testCase
                    project_id: 1
                    project_name: superadmin_personal
                    subject_name: superadmin
                    subject_type: user
                    subject_id: '1'
                    details:
                      history:
                        - field: name
                          old_value: 'Login: valid creds'
                          new_value: 'Login: valid credentials'
                offset: 0
                limit: 300
                total_count: 1
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    Activity:
      title: Activity
      type: object
      description: activity details
      properties:
        id:
          $ref: ../types/identifier.yaml
        created_at:
          type: string
          format: date-time
        event_name:
          type: string
        object_id:
          $ref: ../types/identifier.yaml
        object_name:
          type: string
        object_type:
          type: string
        project_id:
          $ref: ../types/identifier.yaml
        project_name:
          type: string
        subject_name:
          type: string
        subject_type:
          type: string
        subject_id:
          type: string
          description: Identifier of the subject that performed the activity.
        details:
          type: object
          properties:
            history:
              type: array
              items:
                $ref: '#/components/schemas/HistoryField'
    ActivitiesPage:
      title: ActivitiesPage
      allOf:
        - $ref: ../models/Offset.yaml
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/Activity'
    ProjectActivity:
      title: ProjectActivity
      type: object
      description: Details of a single activity performed within a project.
      properties:
        id:
          $ref: ../types/identifier.yaml
        user:
          type: string
          description: The user who performed the activity.
        user_id:
          $ref: ../types/identifier.yaml
        logged_object_id:
          $ref: ../types/identifier.yaml
        last_modified:
          type: string
          format: date-time
        action_type:
          type: string
          description: The type of action performed.
        object_type:
          type: string
          description: The type of object on which the activity was performed.
        project_id:
          $ref: ../types/identifier.yaml
        project_name:
          type: string
        project_key:
          type: string
        object_name:
          type: string
        details:
          type: object
          properties:
            history:
              type: array
              items:
                $ref: '#/components/schemas/HistoryField'
    HistoryField:
      title: HistoryField
      type: object
      properties:
        field:
          type: string
        old_value:
          type: string
        new_value:
          type: string
  responses:
    Error:
      description: Error response
      content:
        application/json:
          schema:
            $ref: ../models/Error.yaml
tags:
  - name: activities
    description: API for working with activities.