openapi: 3.0.3
info:
  title: Activities API
  version: Organization
  description: API Collection for working with activities.
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  contact:
    name: Reingold Shekhtel
    email: reingold_shekhtel@epam.com
servers:
  - url: '{protocol}://{authority}/{basePath}'
    description: ReportPortal server
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
        description: Protocol
      authority:
        default: demo.reportportal.io
        description: Host name and port (if needed) of Report Portal server
      basePath:
        default: api
        description: Base path of Report Portal API
security:
  - BearerAuth: []
paths: {}
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Activity:
      title: Activity
      type: object
      description: activity details
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
        created_at:
          type: string
          format: date-time
        event_name:
          type: string
        object_id:
          type: integer
          exclusiveMinimum: false
          exclusiveMaximum: false
          format: int64
          minimum: 1
        object_name:
          type: string
        object_type:
          type: string
        project_id:
          type: integer
          format: int64
          exclusiveMinimum: false
          minimum: 1
        project_name:
          type: string
        subject_name:
          type: string
        subject_type:
          type: string
        details:
          type: object
          properties:
            history:
              type: array
              items:
                $ref: '#/components/schemas/HistoryField'
    HistoryField:
      title: HistoryField
      type: object
      properties:
        field:
          type: string
        old_value:
          type: string
        new_value:
          type: string
    SearchCriteria:
      title: SearchCriteria
      type: object
      properties:
        filter_key:
          type: string
          description: search by field
        operation:
          type: string
          enum:
            - EQ
            - NE
            - CNT
            - NON_CNT
            - BTW
            - IN
          description: operation to perform for the filter
        value:
          type: string
          description: search value
      required:
        - filter_key
        - value
tags:
  - name: Activities
    description: API Collection for working with activities.
  - name: Organizations
    description: API Collection for working with organizations.
  - name: Projects
    description: API Collection for working with projects.
  - name: Suggestions
    description: API Collection for working with suggestions.
  - name: User API Keys
    description: API Collection for working with user API keys.
