openapi: 3.0.3
info:
  title: ReportPortal Projects API
  version: Organization
  description: API Collection for working with projects.
  contact:
    name: ReportPortal Team
    email: support@reportportal.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: '{host}{basePath}'
    description: ReportPortal server
    variables:
      host:
        default: 'https://demo.reportportal.io'
        description: Host name and port (if needed) of Report Portal server
      basePath:
        default: /api
        description: Base path of Report Portal API
security:
  - BearerAuth: []
paths:
  '/projects/{project_key}/groups':
    parameters:
      - schema:
          type: string
        name: project_key
        in: path
        required: true
        description: Project key.
    get:
      summary: Get all groups of project
      operationId: getGroupsOfProject
      x-permissions:
        - role: ADMINISTRATOR
          access: full
        - role: EDITOR
          access: full
        - role: VIEWER
          access: full
      tags:
        - projects
      parameters:
        - $ref: ../parameters/Offset.yaml
        - $ref: ../parameters/Limit.yaml
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectGroupsPage'
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '402':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
      description: |-
        Get all groups of project.

        ### Authority

        - `ADMINISTRATOR`
        - `EDITOR`
        - `VIEWER`
  '/projects/{project_key}/groups/{group_id}':
    parameters:
      - schema:
          type: string
        name: project_key
        in: path
        required: true
        description: Project key.
      - $ref: ../parameters/GroupId.yaml
    get:
      operationId: getProjectGroupById
      x-permissions:
        - role: ADMINISTRATOR
          access: full
        - role: EDITOR
          access: full
        - role: VIEWER
          access: full
      summary: Get group by id
      description: |-
        Get group by id from project.

        ### Authority

        - `ADMINISTRATOR`
        - `EDITOR`
        - `VIEWER`
      tags:
        - projects
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectGroupInfo'
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '402':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
    put:
      operationId: AddGroupToProjectById
      x-permissions:
        - role: ADMINISTRATOR
          access: full
        - role: EDITOR
          access: full
      summary: Add or update group to project
      description: |-
        Add or update group to project with permission.

        ### Authority

        - `ADMINISTRATOR`
        - `EDITOR`
      tags:
        - projects
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                permission:
                  $ref: ../enums/projectRole.yaml
      responses:
        '200':
          $ref: '#/components/responses/Update'
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '402':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
    delete:
      operationId: DeleteGroupFromProjectById
      x-permissions:
        - role: ADMINISTRATOR
          access: full
        - role: EDITOR
          access: full
      summary: Delete group from project by id
      description: |-
        Delete group from project by id.

        ### Authority

        - `ADMINISTRATOR`
        - `EDITOR`
      tags:
        - projects
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '402':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
  
  '/projects/{project_key}/log-types':
    parameters:
      - schema:
          type: string
        name: project_key
        in: path
        required: true
        description: Project key.
    get:
      summary: Get log types of project
      operationId: getLogTypes
      x-permissions:
        - role: ADMINISTRATOR
          access: full
        - role: EDITOR
          access: full
        - role: VIEWER
          access: full
      tags:
        - projects
      description: |-
        Get log types of project.

        ### Authority

        - `ADMINISTRATOR`
        - `EDITOR`
        - `VIEWER`
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    description: List of available log types for the project.
                    type: array
                    items:
                      $ref: '#/components/schemas/LogType'
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '402':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
    post:
      summary: Create new log type
      operationId: createLogType
      x-permissions:
        - role: ADMINISTRATOR
          access: full
        - role: EDITOR
          access: full
      tags:
        - projects
      description: |-
        Create new log type in project.

        ### Authority

        - `ADMINISTRATOR`
        - `EDITOR`                                                       
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogType'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogType'
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '402':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
  
  '/projects/{project_key}/log-types/{log_type_id}':
    parameters:
      - schema:
          type: string
        name: project_key
        in: path
        required: true
        description: Project key.
      - schema:
          type: integer
          format: int64
          minimum: 1
        name: log_type_id
        in: path
        required: true
        description: Log type identifier.
    get:
      summary: Get log type by id
      operationId: getLogTypeById
      x-permissions:
        - role: ADMINISTRATOR
          access: full
        - role: EDITOR
          access: full
        - role: VIEWER
          access: full
      tags:
        - projects
      description: |-
        Get log type in project by id.

        ### Authority
        - `ADMINISTRATOR`
        - `EDITOR`
        - `VIEWER`
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogType'
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '402':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
    put:
      summary: Update log type
      operationId: updateLogTypeById
      x-permissions:
        - role: ADMINISTRATOR
          access: full
        - role: EDITOR
          access: full
      tags:
        - projects
      description: |-
        Update log type in project by id.

        ### Authority

        - `ADMINISTRATOR`
        - `EDITOR`
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogType'
      responses:
        '200':
          $ref: '#/components/responses/Update'
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '402':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
    delete:
      summary: Delete log type
      operationId: deleteLogTypeById
      x-permissions:
        - role: ADMINISTRATOR
          access: full
        - role: EDITOR
          access: full
      tags:
        - projects
      description: |-
        Delete log type from project by id.

        ### Authority

        - `ADMINISTRATOR`
        - `EDITOR`
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '402':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    ProjectGroupsPage:
      title: ProjectGroupsPage
      allOf:
        - $ref: ../models/Offset.yaml
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/ProjectGroupInfo'
    ProjectGroupInfo:
      title: Project group
      description: Information about project group.
      type: object
      properties:
        id:
          $ref: ../types/identifier.yaml
        uuid:
          type: string
          format: uuid
          description: Group identifier for external usage.
        name:
          $ref: ../types/name.yaml
        slug:
          $ref: ../types/slug.yaml
        permission:
          $ref: ../enums/projectRole.yaml
        added_at:
          type: string
          format: date-time
          description: Timestamp of project adding to group.
        updated_at:
          type: string
          format: date-time
          description: Timestamp of project updating in group.
        stats:
          type: object
          description: Group statistics.
          properties:
            users_count:
              type: integer
              format: int32
              description: Number of users in the group.
    LogType:
      title: Project Log Type
      description: Information about log type in project.s
      type: object
      properties:
        id:
          $ref: ../types/identifier.yaml
        name:
          type: string
          minLength: 3
          maxLength: 16
          pattern: '^[A-Za-z0-9 ]+$'
          description: Name of log type. Unique within project.
        level:
          type: integer
          minimum: 1
          maximum: 59999
          description: Numeric value of log type. Unique within project.
        style:
          $ref: '#/components/schemas/LogTypeStyle'
        is_system:
          type: boolean
          default: false
          description: |-
            Indicates if the log type is a system log type.
            You cannot modify its name and log level or delete system log types.
          readOnly: true
        is_filterable:
          type: boolean
          default: false
          description: Indicates if the log level is filterable.
      required:
        - name
        - level
    LogTypeStyle:
      title: Log Type Style
      description: Style information for a log type.
      type: object
      properties:
        label_color:
          type: string
          format: hex-color
          default: '#4DB6AC'
          description: Color associated with the log type. Hex format.
          pattern: '^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$'
        background_color:
          type: string
          format: hex-color
          default: '#FFFFFF'
          description: Background color associated with the log type. Hex format.
          pattern: '^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$'
        text_color:
          type: string
          format: hex-color
          default: '#464547'
          description: Text color associated with the log type. Hex format.
          pattern: '^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$'
        text_style:
          type: string
          description: Text style associated with the log type.
          enum:
            - bold
            - normal
          default: normal
  responses:
    Error:
      description: Error response
      content:
        application/json:
          schema:
            $ref: ../models/Error.yaml
    Update:
      description: Successful update response
      content:
        application/json:
          schema:
            title: Successful update
            type: object
            properties:
              message:
                type: string
                default: The update was completed successfully.
tags:
  - name: projects
    description: API for working with projects.
