openapi: 3.0.3
info:
  title: ReportPortal Projects API
  version: Organization
  description: API Collection for working with projects.
  contact:
    name: ReportPortal Team
    email: support@reportportal.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: '{host}{basePath}'
    description: ReportPortal server
    variables:
      host:
        default: 'https://demo.reportportal.io'
        description: Host name and port (if needed) of Report Portal server
      basePath:
        default: /api
        description: Base path of Report Portal API
security:
  - BearerAuth: []
paths:
  '/projects/{project_key}/groups':
    parameters:
      - schema:
          type: string
        name: project_key
        in: path
        required: true
        description: Project key.
    get:
      summary: Get all groups of project
      operationId: getGroupsOfProject
      x-permissions:
        - role: ADMINISTRATOR
          access: full
        - role: EDITOR
          access: full
        - role: VIEWER
          access: full
      tags:
        - projects
      parameters:
        - $ref: ../parameters/Offset.yaml
        - $ref: ../parameters/Limit.yaml
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectGroupsPage'
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '402':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
      description: |-
        Get all groups of project.

        ### Authority

        - `ADMINISTRATOR`
        - `EDITOR`
        - `VIEWER`
  '/projects/{project_key}/groups/{group_id}':
    parameters:
      - schema:
          type: string
        name: project_key
        in: path
        required: true
        description: Project key.
      - $ref: ../parameters/GroupId.yaml
    get:
      operationId: getProjectGroupById
      x-permissions:
        - role: ADMINISTRATOR
          access: full
        - role: EDITOR
          access: full
        - role: VIEWER
          access: full
      summary: Get group by id
      description: |-
        Get group by id from project.

        ### Authority

        - `ADMINISTRATOR`
        - `EDITOR`
        - `VIEWER`
      tags:
        - projects
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectGroupInfo'
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '402':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
    put:
      operationId: AddGroupToProjectById
      x-permissions:
        - role: ADMINISTRATOR
          access: full
        - role: EDITOR
          access: full
      summary: Add or update group to project
      description: |-
        Add or update group to project with permission.

        ### Authority

        - `ADMINISTRATOR`
        - `EDITOR`
      tags:
        - projects
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                permission:
                  $ref: ../enums/projectRole.yaml
      responses:
        '200':
          $ref: '#/components/responses/Update'
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '402':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
    delete:
      operationId: DeleteGroupFromProjectById
      x-permissions:
        - role: ADMINISTRATOR
          access: full
        - role: EDITOR
          access: full
      summary: Delete group from project by id
      description: |-
        Delete group from project by id.

        ### Authority

        - `ADMINISTRATOR`
        - `EDITOR`
      tags:
        - projects
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '402':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    ProjectGroupsPage:
      title: ProjectGroupsPage
      allOf:
        - $ref: ../models/Offset.yaml
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/ProjectGroupInfo'
    ProjectGroupInfo:
      title: Project group
      description: Information about project group.
      type: object
      properties:
        id:
          $ref: ../types/identifier.yaml
        uuid:
          type: string
          format: uuid
          description: Group identifier for external usage.
        name:
          $ref: ../types/name.yaml
        slug:
          $ref: ../types/slug.yaml
        permission:
          $ref: ../enums/projectRole.yaml
        added_at:
          type: string
          format: date-time
          description: Timestamp of project adding to group.
        updated_at:
          type: string
          format: date-time
          description: Timestamp of project updating in group.
        stats:
          type: object
          description: Group statistics.
          properties:
            users_count:
              type: integer
              format: int32
              description: Number of users in the group.
  responses:
    Error:
      description: Error problem response
      content:
        application/problem+json:
          schema:
            $ref: ../models/Problem.yaml
    Update:
      description: Successful update response
      content:
        application/json:
          schema:
            title: Successful update
            type: object
            properties:
              message:
                type: string
                default: The update was completed successfully.
tags:
  - name: projects
    description: API for working with projects.
