openapi: 3.0.3
info:
  title: Projects API
  version: Organization
  description: API Collection for working with projects.
  contact:
    name: ReportPortal Team
    email: support@reportportal.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: '{host}{basePath}'
    description: ReportPortal server
    variables:
      host:
        default: https://demo.reportportal.io
        description: Host name and port (if needed) of Report Portal server
      basePath:
        default: /api
        description: Base path of Report Portal API
security:
  - BearerAuth: []
paths:
  '/projects/{project_id}/users':
    parameters:
      - schema:
          type: string
        name: project_id
        in: path
        required: true
    post:
      summary: Assign user to project
      operationId: post-projects-project_id-users
      description: '#ToDo'
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectUser'
  '/projects/{project_id}/users/{user_id}':
    parameters:
      - schema:
          type: string
        name: project_id
        in: path
        required: true
      - schema:
          type: string
        name: user_id
        in: path
        required: true
    put:
      summary: Update project user
      operationId: put-projects-project_id-users-user_id
      responses:
        '204':
          description: No Content
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                project_role:
                  $ref: ../enums/projectRole.yaml
    delete:
      summary: Unassign user from project
      operationId: delete-projects-project_id-users-user_id
      responses:
        '200':
          description: OK
      description: |-
        ### Authority

        - `ADMINISTRATOR`
        - `MANAGER`
        - `MEMBER`

        ### Member authority

        - `EDITOR` - can delete any user.
        - `VIEWER` - can delete themself.
  '/projects/{project_name}/groups':
    parameters:
      - schema:
          type: string
        name: project_name
        in: path
        required: true
        description: Project name.
    get:
      summary: Get all groups of project
      operationId: getGroupsOfProject
      tags:
        - Projects
      parameters:
        - $ref: ../parameters/Offset.yaml
        - $ref: ../parameters/Limit.yaml
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectGroupsPage'
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '402':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
      description: Get all groups of project.
  '/projects/{project_name}/groups/{group_id}':
    parameters:
      - schema:
          type: string
        name: project_name
        in: path
        required: true
        description: Project name.
      - $ref: ../parameters/GroupId.yaml
    get:
      summary: Get group by id
      description: Get group by id from project.
      operationId: getProjectGroupById
      tags:
        - Projects
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectGroupInfo'
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '402':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
    put:
      summary: Add or update group to project
      description: Add or update group to project with permission.
      operationId: AddGroupToProjectById
      tags:
        - Projects
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                permission:
                  $ref: ../enums/projectRole.yaml
      responses:
        '200':
          $ref: '#/components/responses/Update'
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '402':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
    delete:
      summary: Delete group from project by id
      description: Delete group from project by id.
      operationId: DeleteGroupFromProjectById
      tags:
        - Projects
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/Error'
        '401':
          $ref: '#/components/responses/Error'
        '402':
          $ref: '#/components/responses/Error'
        '403':
          $ref: '#/components/responses/Error'
        '404':
          $ref: '#/components/responses/Error'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    ProjectUser:
      title: ProjectUser
      type: object
      properties:
        id:
          $ref: ../types/userId.yaml
        project_role:
          $ref: ../enums/projectRole.yaml
    ProjectGroupsPage:
      title: ProjectGroupsPage
      allOf:
        - $ref: ../models/Offset.yaml
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/ProjectGroup'
    ProjectGroup:
      title: Project group
      description: Information about project group.
      type: object
      properties:
        project_role:
          $ref: ../enums/projectRole.yaml
        added_at:
          type: string
          format: date-time
          description: Timestamp of project adding to group.
          x-stoplight:
            id: 10gkz1piwd02r
        updated_at:
          type: string
          format: date-time
          description: Timestamp of project updating in group.
        group:
          $ref: ../models/group/GroupInfo.yaml
tags:
  - name: Projects
    description: Operations with projects
