name: OpenAPI Build

on:
  push:
    paths:
      - 'api/openapi/apis/**'

jobs:
  build:
    name: OpenAPI Build Bundle
    runs-on: ubuntu-latest
    container: node:21
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configurate Git Safe Directory
        run: git config --global --add safe.directory /__w/api-registry/api-registry

      - name: Verify OpenAPI
        run: |
          make lint-all

      - name: Update main specification
        run: |
          make join

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add api/openapi/reportportal-api.yaml
          git commit -m "Update reportportal-api.yaml"
          git push

      - name: Bundle OpenAPI
        run: |
          make bundle

      - name: Upload OpenAPI bundles as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: openapi-bundles
          path: build/openapi/
