name: OpenAPI Build

on:
  push:
    paths:
      - api/openapi/*.yaml

jobs:
  buid:
    name: OpenAPI Build Bundle
    runs-on: ubuntu-latest
    container: node:21
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install JQ
        run: apt-get update && apt-get install -y jq

      - name: Configurate Git Safe Directory
        run: git config --global --add safe.directory /__w/reportportal-common-api/reportportal-common-api

      - name: Determine changed OpenAPI files
        id: changed_files
        uses: dorny/paths-filter@v3
        with:
          list-files: json
          filters: |
            openapi:
              - 'api/openapi/*.yaml'

      - name: Verify OpenAPI
        if: steps.changed_files.outputs.openapi == 'true'
        run: |
          FILES_JSON=${{ steps.changed_files.outputs.openapi_files }}
          FILES=$(echo $FILES_JSON | jq -r '.[]')
          echo "Changed OpenAPI files: $FILES"
          for FILE in $FILES; do
            npx @redocly/cli@latest lint "$FILE"
          done

      - name: Bundle OpenAPI
        if: steps.changed_files.outputs.openapi == 'true'
        run: |
          FILES_JSON=${{ steps.changed_files.outputs.openapi_files }}
          FILES=$(echo $FILES_JSON | jq -r '.[]')
          for FILE in $FILES; do
            npx @redocly/cli@latest bundle "$FILE" -d -o api/openapi/bundles/$(basename "$FILE").yaml
          done