name: OpenAPI Build

on:
  push:
    paths:
      - api/openapi/*.yaml

jobs:
  build:
    name: OpenAPI Build Bundle
    runs-on: ubuntu-latest
    container: node:21
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configurate Git Safe Directory
        run: git config --global --add safe.directory /__w/reportportal-common-api/reportportal-common-api

      - name: Create OpenAPI bundles directory
        run: mkdir -p api/openapi/bundles/

      - name: Determine changed OpenAPI files
        id: changed_files
        uses: dorny/paths-filter@v3
        with:
          list-files: shell
          filters: |
            openapi:
              - 'api/openapi/*.yaml'

      - name: Verify OpenAPI
        if: steps.changed_files.outputs.openapi == 'true'
        run: |
          echo "${{ steps.changed_files.outputs.openapi_files }}" | xargs -n 1 | while read FILE; do
            npx @redocly/cli@latest lint "$FILE"
          done

      - name: Bundle OpenAPI
        if: steps.changed_files.outputs.openapi == 'true'
        run: |
          echo "${{ steps.changed_files.outputs.openapi_files }}" | xargs -n 1 | while read FILE; do
            npx @redocly/cli@latest bundle "$FILE" -d -o api/openapi/bundles/$(basename "$FILE").yaml
          done