name: buf-pull-request

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - readme.md
      - README.md
      - CHANGELOG.md
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Buf CLI
        uses: bufbuild/buf-setup-action@v1.13.1
        with:
          github_token: ${{ github.token }}
      - name: Check for linting errors
        uses: bufbuild/buf-lint-action@v1.0.3
        with:
          input: 'api/proto'
      - name: Check for breaking changes
        uses: bufbuild/buf-breaking-action@v1.1.2
        with:
          input: 'api/proto'
          # The 'main' branch of the GitHub repository that defines the module.
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=main,ref=HEAD~1,subdir=api/proto'